CREATE TABLE paises (
pais_ID           integer IDENTITY NOT NULL,
pais_descricao    varchar(100),
pais_sigla        varchar(020),
CONSTRAINT PK_paises PRIMARY KEY CLUSTERED 
(
	pais_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
);
GO
CREATE NONCLUSTERED INDEX id_paises_000 ON paises
(
	pais_descricao ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


